[default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 1000

remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@chainlink=node_modules/@chainlink/',
    '@uniswap=node_modules/@uniswap/'
]

## set only when the `hardhat` profile is selected
[hardhat]
src = "src"
out = "artifacts"
libs = ["node_modules"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config